In [ ]:
importing the Libraries

In [3]:
import pandas as pd
import numpy as np
import pickle
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

In [5]:
df = pd.read_csv('IceCreamData.csv')

In [7]:
df.head()

Temperature     Revenue
0    24.566884  534.799028
1    26.005191  625.190122
2    27.790554  660.632289
3    20.595335  487.706960
4    11.503498  316.240194

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Temperature  500 non-null    float64
 1   Revenue      500 non-null    float64
dtypes: float64(2)
memory usage: 7.9 KB


In [11]:
x = df['Temperature']
y = df['Revenue']

In [15]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2)

In [17]:
len(x_train)

400

In [19]:
len(y_train)

400

In [21]:
len(x_test)

100

In [23]:
model = LinearRegression()

In [25]:
y_test.ndim

1

In [27]:
x_train.ndim

1

In [29]:
np.array([x_train]).ndim

2

In [31]:
model.fit(np.array([x_train]).reshape(-1,1),y_train)

LinearRegression()

In [33]:
y_pred = model.predict(np.array(x_test).reshape(-1,1))

In [35]:
y_pred

array([393.67193066, 438.47971957, 395.95136024, 775.69935848,
       249.86793423, 528.17539934, 304.92522473, 266.37207554,
       450.53238736, 697.28817964, 892.68081974, 575.39313131,
       255.34492526, 460.28888288, 408.60837995, 685.96568766,
       484.14809842, 671.05346218, 860.18125554, 369.19781627,
       469.12974702, 803.55456428, 621.45267248, 909.64631195,
       519.41932887, 441.40499846, 570.98750454, 476.73473272,
       415.99929904, 527.23226611, 396.83279533, 452.03045044,
       589.27590826, 663.97525643, 602.62071114, 586.42274676,
       683.567696  , 622.96629437, 493.23999556, 442.87488504,
       605.41565617, 759.67670015, 537.05000485, 468.69112309,
       893.25492869, 605.32759607, 792.84540596, 704.90868188,
       197.29884454, 585.35574366, 591.97057228, 551.01338738,
       567.28067673, 468.11966192, 944.42389697, 643.20154813,
       284.8558629 , 169.72106754, 539.84604148, 591.90491651,
       577.01159418, 351.36565918, 420.6744991 , 443.44

In [37]:
y_test

23     374.231135
382    410.860905
85     406.579249
338    771.789537
339    235.364643
          ...    
172    539.527740
87     344.688765
243    367.052376
163    648.554644
304    714.560056
Name: Revenue, Length: 100, dtype: float64

In [39]:
r2_score(y_test,y_pred)

0.984659829372867

In [44]:
model.predict([[34]])

array([774.37593023])

In [46]:
model.predict([[1]])

array([66.24029909])

In [47]:
with open('model.pkl','wb') as files:
    pickle.dump(model,files)